# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='common.proto',
  package='',
  serialized_pb='\n\x0c\x63ommon.proto\"{\n\x17PropertyTypeConstraints\x12\x18\n\x10\x44oubleTypeMaxVal\x18\x01 \x01(\x01\x12\x18\n\x10\x44oubleTypeMinVal\x18\x02 \x01(\x01\x12\x15\n\rIntTypeMaxVal\x18\x03 \x01(\x03\x12\x15\n\rIntTypeMinVal\x18\x04 \x01(\x03\"\xc0\x01\n\x08Property\x12\x12\n\npropertyId\x18\x01 \x02(\t\x12\x1b\n\x04type\x18\x02 \x02(\x0e\x32\r.PropertyType\x12\x0e\n\x06string\x18\x03 \x01(\t\x12\x0c\n\x04\x62ool\x18\x04 \x01(\x08\x12\x0b\n\x03int\x18\x05 \x01(\x03\x12\x0e\n\x06\x64ouble\x18\x06 \x01(\x01\x12\r\n\x05\x62ytes\x18\x07 \x01(\x0c\x12\x1a\n\x12\x62ytes_content_type\x18\x08 \x01(\t\x12\x1d\n\nproperties\x18\t \x03(\x0b\x32\t.Property*\x83\x01\n\x0cPropertyType\x12\x0f\n\x0bUnknownType\x10\x00\x12\x0e\n\nStringType\x10\x01\x12\x0f\n\x0b\x42ooleanType\x10\x02\x12\x0b\n\x07IntType\x10\x03\x12\x0e\n\nDoubleType\x10\x04\x12\r\n\tBytesType\x10\x05\x12\x15\n\x11SubPropertiesType\x10\x06')

_PROPERTYTYPE = _descriptor.EnumDescriptor(
  name='PropertyType',
  full_name='PropertyType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UnknownType', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='StringType', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BooleanType', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IntType', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DoubleType', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BytesType', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SubPropertiesType', index=6, number=6,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=337,
  serialized_end=468,
)

PropertyType = enum_type_wrapper.EnumTypeWrapper(_PROPERTYTYPE)
UnknownType = 0
StringType = 1
BooleanType = 2
IntType = 3
DoubleType = 4
BytesType = 5
SubPropertiesType = 6



_PROPERTYTYPECONSTRAINTS = _descriptor.Descriptor(
  name='PropertyTypeConstraints',
  full_name='PropertyTypeConstraints',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='DoubleTypeMaxVal', full_name='PropertyTypeConstraints.DoubleTypeMaxVal', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='DoubleTypeMinVal', full_name='PropertyTypeConstraints.DoubleTypeMinVal', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='IntTypeMaxVal', full_name='PropertyTypeConstraints.IntTypeMaxVal', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='IntTypeMinVal', full_name='PropertyTypeConstraints.IntTypeMinVal', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=16,
  serialized_end=139,
)


_PROPERTY = _descriptor.Descriptor(
  name='Property',
  full_name='Property',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='propertyId', full_name='Property.propertyId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='Property.type', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='string', full_name='Property.string', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bool', full_name='Property.bool', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='int', full_name='Property.int', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='double', full_name='Property.double', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bytes', full_name='Property.bytes', index=6,
      number=7, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bytes_content_type', full_name='Property.bytes_content_type', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='properties', full_name='Property.properties', index=8,
      number=9, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=142,
  serialized_end=334,
)

_PROPERTY.fields_by_name['type'].enum_type = _PROPERTYTYPE
_PROPERTY.fields_by_name['properties'].message_type = _PROPERTY
DESCRIPTOR.message_types_by_name['PropertyTypeConstraints'] = _PROPERTYTYPECONSTRAINTS
DESCRIPTOR.message_types_by_name['Property'] = _PROPERTY

class PropertyTypeConstraints(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PROPERTYTYPECONSTRAINTS

  # @@protoc_insertion_point(class_scope:PropertyTypeConstraints)

class Property(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PROPERTY

  # @@protoc_insertion_point(class_scope:Property)


# @@protoc_insertion_point(module_scope)
