# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: commands.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import common_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='commands.proto',
  package='',
  serialized_pb='\n\x0e\x63ommands.proto\x1a\x0c\x63ommon.proto\"l\n\x16SetDevicePropertiesMsg\x12\x0e\n\x06hostId\x18\x01 \x02(\t\x12\x10\n\x08\x64\x65viceId\x18\x02 \x02(\t\x12\x1d\n\nproperties\x18\x03 \x03(\x0b\x32\t.Property\x12\x11\n\trequestId\x18\x05 \x01(\t')




_SETDEVICEPROPERTIESMSG = _descriptor.Descriptor(
  name='SetDevicePropertiesMsg',
  full_name='SetDevicePropertiesMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hostId', full_name='SetDevicePropertiesMsg.hostId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='deviceId', full_name='SetDevicePropertiesMsg.deviceId', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='properties', full_name='SetDevicePropertiesMsg.properties', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='requestId', full_name='SetDevicePropertiesMsg.requestId', index=3,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=32,
  serialized_end=140,
)

_SETDEVICEPROPERTIESMSG.fields_by_name['properties'].message_type = common_pb2._PROPERTY
DESCRIPTOR.message_types_by_name['SetDevicePropertiesMsg'] = _SETDEVICEPROPERTIESMSG

class SetDevicePropertiesMsg(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SETDEVICEPROPERTIESMSG

  # @@protoc_insertion_point(class_scope:SetDevicePropertiesMsg)


# @@protoc_insertion_point(module_scope)
