# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: configurations.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import common_pb2
import descriptions_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='configurations.proto',
  package='',
  serialized_pb='\n\x14\x63onfigurations.proto\x1a\x0c\x63ommon.proto\x1a\x12\x64\x65scriptions.proto\"]\n\nHostConfig\x12)\n\x0fhostDescription\x18\x01 \x02(\x0b\x32\x10.HostDescription\x12$\n\rdeviceConfigs\x18\x02 \x03(\x0b\x32\r.DeviceConfig\"C\n\x0c\x44\x65viceConfig\x12\x10\n\x08\x64\x65viceId\x18\x01 \x02(\t\x12!\n\x0einitProperties\x18\x02 \x03(\x0b\x32\t.Property')




_HOSTCONFIG = _descriptor.Descriptor(
  name='HostConfig',
  full_name='HostConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hostDescription', full_name='HostConfig.hostDescription', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='deviceConfigs', full_name='HostConfig.deviceConfigs', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=58,
  serialized_end=151,
)


_DEVICECONFIG = _descriptor.Descriptor(
  name='DeviceConfig',
  full_name='DeviceConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='deviceId', full_name='DeviceConfig.deviceId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='initProperties', full_name='DeviceConfig.initProperties', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=153,
  serialized_end=220,
)

_HOSTCONFIG.fields_by_name['hostDescription'].message_type = descriptions_pb2._HOSTDESCRIPTION
_HOSTCONFIG.fields_by_name['deviceConfigs'].message_type = _DEVICECONFIG
_DEVICECONFIG.fields_by_name['initProperties'].message_type = common_pb2._PROPERTY
DESCRIPTOR.message_types_by_name['HostConfig'] = _HOSTCONFIG
DESCRIPTOR.message_types_by_name['DeviceConfig'] = _DEVICECONFIG

class HostConfig(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _HOSTCONFIG

  # @@protoc_insertion_point(class_scope:HostConfig)

class DeviceConfig(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DEVICECONFIG

  # @@protoc_insertion_point(class_scope:DeviceConfig)


# @@protoc_insertion_point(module_scope)
