# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: descriptions.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='descriptions.proto',
  package='',
  serialized_pb='\n\x12\x64\x65scriptions.proto\"\xd2\x01\n\x0fHostDescription\x12\x0e\n\x06hostId\x18\x01 \x02(\t\x12\x11\n\thostLabel\x18\x02 \x02(\t\x12.\n\x12\x64\x65viceDescriptions\x18\x03 \x03(\x0b\x32\x12.DeviceDescription\x12\x36\n\x18hostPropertyDescriptions\x18\x04 \x03(\x0b\x32\x14.PropertyDescription\x12\x34\n\x17hostCommandDescriptions\x18\x05 \x03(\x0b\x32\x13.CommandDescription\"\xe8\x01\n\x11\x44\x65viceDescription\x12\x10\n\x08\x64\x65viceId\x18\x01 \x02(\t\x12\x13\n\x0b\x64\x65viceLabel\x18\x02 \x02(\t\x12\x12\n\ndeviceType\x18\x03 \x02(\t\x12&\n\nsubDevices\x18\x04 \x03(\x0b\x32\x12.DeviceDescription\x12\x38\n\x1a\x64\x65vicePropertyDescriptions\x18\x05 \x03(\x0b\x32\x14.PropertyDescription\x12\x36\n\x19\x64\x65viceCommandDescriptions\x18\x06 \x03(\x0b\x32\x13.CommandDescription\"\xdc\x01\n\x13PropertyDescription\x12\x12\n\npropertyId\x18\x01 \x02(\t\x12\x15\n\rpropertyLabel\x18\x02 \x02(\t\x12#\n\x0cpropertyType\x18\x03 \x02(\x0e\x32\r.PropertyType\x12-\n\x0b\x63onstraints\x18\x04 \x01(\x0b\x32\x18.PropertyTypeConstraints\x12\x35\n\x17subPropertyDescriptions\x18\x05 \x03(\x0b\x32\x14.PropertyDescription\x12\x0f\n\x07persist\x18\x06 \x01(\x08\"x\n\x12\x43ommandDescription\x12\x11\n\tcommandId\x18\x01 \x02(\t\x12\x14\n\x0c\x63ommandLabel\x18\x02 \x02(\t\x12\x39\n\x1b\x63ommandArgumentDescriptions\x18\x03 \x03(\x0b\x32\x14.PropertyDescription\"{\n\x17PropertyTypeConstraints\x12\x18\n\x10\x64oubleTypeMaxVal\x18\x01 \x01(\x01\x12\x18\n\x10\x64oubleTypeMinVal\x18\x02 \x01(\x01\x12\x15\n\rintTypeMaxVal\x18\x03 \x01(\x03\x12\x15\n\rintTypeMinVal\x18\x04 \x01(\x03*\x83\x01\n\x0cPropertyType\x12\x0f\n\x0bUnknownType\x10\x00\x12\x0e\n\nStringType\x10\x01\x12\x0f\n\x0b\x42ooleanType\x10\x02\x12\x0b\n\x07IntType\x10\x03\x12\x0e\n\nDoubleType\x10\x04\x12\r\n\tBytesType\x10\x05\x12\x15\n\x11SubPropertiesType\x10\x06')

_PROPERTYTYPE = _descriptor.EnumDescriptor(
  name='PropertyType',
  full_name='PropertyType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UnknownType', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='StringType', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BooleanType', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IntType', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DoubleType', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BytesType', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SubPropertiesType', index=6, number=6,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=941,
  serialized_end=1072,
)

PropertyType = enum_type_wrapper.EnumTypeWrapper(_PROPERTYTYPE)
UnknownType = 0
StringType = 1
BooleanType = 2
IntType = 3
DoubleType = 4
BytesType = 5
SubPropertiesType = 6



_HOSTDESCRIPTION = _descriptor.Descriptor(
  name='HostDescription',
  full_name='HostDescription',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hostId', full_name='HostDescription.hostId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hostLabel', full_name='HostDescription.hostLabel', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='deviceDescriptions', full_name='HostDescription.deviceDescriptions', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hostPropertyDescriptions', full_name='HostDescription.hostPropertyDescriptions', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hostCommandDescriptions', full_name='HostDescription.hostCommandDescriptions', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=23,
  serialized_end=233,
)


_DEVICEDESCRIPTION = _descriptor.Descriptor(
  name='DeviceDescription',
  full_name='DeviceDescription',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='deviceId', full_name='DeviceDescription.deviceId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='deviceLabel', full_name='DeviceDescription.deviceLabel', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='deviceType', full_name='DeviceDescription.deviceType', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='subDevices', full_name='DeviceDescription.subDevices', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='devicePropertyDescriptions', full_name='DeviceDescription.devicePropertyDescriptions', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='deviceCommandDescriptions', full_name='DeviceDescription.deviceCommandDescriptions', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=236,
  serialized_end=468,
)


_PROPERTYDESCRIPTION = _descriptor.Descriptor(
  name='PropertyDescription',
  full_name='PropertyDescription',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='propertyId', full_name='PropertyDescription.propertyId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='propertyLabel', full_name='PropertyDescription.propertyLabel', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='propertyType', full_name='PropertyDescription.propertyType', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='constraints', full_name='PropertyDescription.constraints', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='subPropertyDescriptions', full_name='PropertyDescription.subPropertyDescriptions', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='persist', full_name='PropertyDescription.persist', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=471,
  serialized_end=691,
)


_COMMANDDESCRIPTION = _descriptor.Descriptor(
  name='CommandDescription',
  full_name='CommandDescription',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='commandId', full_name='CommandDescription.commandId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='commandLabel', full_name='CommandDescription.commandLabel', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='commandArgumentDescriptions', full_name='CommandDescription.commandArgumentDescriptions', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=693,
  serialized_end=813,
)


_PROPERTYTYPECONSTRAINTS = _descriptor.Descriptor(
  name='PropertyTypeConstraints',
  full_name='PropertyTypeConstraints',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='doubleTypeMaxVal', full_name='PropertyTypeConstraints.doubleTypeMaxVal', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='doubleTypeMinVal', full_name='PropertyTypeConstraints.doubleTypeMinVal', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='intTypeMaxVal', full_name='PropertyTypeConstraints.intTypeMaxVal', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='intTypeMinVal', full_name='PropertyTypeConstraints.intTypeMinVal', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=815,
  serialized_end=938,
)

_HOSTDESCRIPTION.fields_by_name['deviceDescriptions'].message_type = _DEVICEDESCRIPTION
_HOSTDESCRIPTION.fields_by_name['hostPropertyDescriptions'].message_type = _PROPERTYDESCRIPTION
_HOSTDESCRIPTION.fields_by_name['hostCommandDescriptions'].message_type = _COMMANDDESCRIPTION
_DEVICEDESCRIPTION.fields_by_name['subDevices'].message_type = _DEVICEDESCRIPTION
_DEVICEDESCRIPTION.fields_by_name['devicePropertyDescriptions'].message_type = _PROPERTYDESCRIPTION
_DEVICEDESCRIPTION.fields_by_name['deviceCommandDescriptions'].message_type = _COMMANDDESCRIPTION
_PROPERTYDESCRIPTION.fields_by_name['propertyType'].enum_type = _PROPERTYTYPE
_PROPERTYDESCRIPTION.fields_by_name['constraints'].message_type = _PROPERTYTYPECONSTRAINTS
_PROPERTYDESCRIPTION.fields_by_name['subPropertyDescriptions'].message_type = _PROPERTYDESCRIPTION
_COMMANDDESCRIPTION.fields_by_name['commandArgumentDescriptions'].message_type = _PROPERTYDESCRIPTION
DESCRIPTOR.message_types_by_name['HostDescription'] = _HOSTDESCRIPTION
DESCRIPTOR.message_types_by_name['DeviceDescription'] = _DEVICEDESCRIPTION
DESCRIPTOR.message_types_by_name['PropertyDescription'] = _PROPERTYDESCRIPTION
DESCRIPTOR.message_types_by_name['CommandDescription'] = _COMMANDDESCRIPTION
DESCRIPTOR.message_types_by_name['PropertyTypeConstraints'] = _PROPERTYTYPECONSTRAINTS

class HostDescription(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _HOSTDESCRIPTION

  # @@protoc_insertion_point(class_scope:HostDescription)

class DeviceDescription(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DEVICEDESCRIPTION

  # @@protoc_insertion_point(class_scope:DeviceDescription)

class PropertyDescription(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PROPERTYDESCRIPTION

  # @@protoc_insertion_point(class_scope:PropertyDescription)

class CommandDescription(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _COMMANDDESCRIPTION

  # @@protoc_insertion_point(class_scope:CommandDescription)

class PropertyTypeConstraints(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PROPERTYTYPECONSTRAINTS

  # @@protoc_insertion_point(class_scope:PropertyTypeConstraints)


# @@protoc_insertion_point(module_scope)
