# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpx.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import tasktypes_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='rpx.proto',
  package='',
  serialized_pb='\n\trpx.proto\x1a\x0ftasktypes.proto\"A\n\nRpxMessage\x12\x0f\n\x07version\x18\x01 \x02(\t\x12\"\n\x0e\x66irstOperation\x18\x02 \x02(\x0b\x32\n.Operation\"\x87\x01\n\tOperation\x12\x1d\n\x15\x64\x65layBeforeStartInSec\x18\x01 \x02(\x01\x12\"\n\x1a\x62lockUntilAllTasksComplete\x18\x02 \x02(\x08\x12\x14\n\x05tasks\x18\x03 \x03(\x0b\x32\x05.Task\x12!\n\rnextOperation\x18\x04 \x01(\x0b\x32\n.Operation\"\x93\x03\n\x04Task\x12 \n\x08taskType\x18\x01 \x02(\x0e\x32\x0e.Task.TaskType\x12\x39\n\x17setDevicePropertiesTask\x18\x02 \x01(\x0b\x32\x18.SetDevicePropertiesTask\x12\x33\n\x14\x64oDeviceCommandsTask\x18\x03 \x01(\x0b\x32\x15.DoDeviceCommandsTask\x12\x35\n\x15setHostPropertiesTask\x18\x04 \x01(\x0b\x32\x16.SetHostPropertiesTask\x12/\n\x12\x64oHostCommandsTask\x18\x05 \x01(\x0b\x32\x13.DoHostCommandsTask\"\x90\x01\n\x08TaskType\x12\x0f\n\x0bUnknownType\x10\x00\x12\x1f\n\x1bSetDevicePropertiesTaskType\x10\x01\x12\x0f\n\x0b\x42ooleanType\x10\x02\x12\x0b\n\x07IntType\x10\x03\x12\x0e\n\nDoubleType\x10\x04\x12\r\n\tBytesType\x10\x05\x12\x15\n\x11SubPropertiesType\x10\x06')



_TASK_TASKTYPE = _descriptor.EnumDescriptor(
  name='TaskType',
  full_name='Task.TaskType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UnknownType', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SetDevicePropertiesTaskType', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BooleanType', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IntType', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DoubleType', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BytesType', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SubPropertiesType', index=6, number=6,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=495,
  serialized_end=639,
)


_RPXMESSAGE = _descriptor.Descriptor(
  name='RpxMessage',
  full_name='RpxMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='RpxMessage.version', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='firstOperation', full_name='RpxMessage.firstOperation', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=30,
  serialized_end=95,
)


_OPERATION = _descriptor.Descriptor(
  name='Operation',
  full_name='Operation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='delayBeforeStartInSec', full_name='Operation.delayBeforeStartInSec', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='blockUntilAllTasksComplete', full_name='Operation.blockUntilAllTasksComplete', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tasks', full_name='Operation.tasks', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nextOperation', full_name='Operation.nextOperation', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=98,
  serialized_end=233,
)


_TASK = _descriptor.Descriptor(
  name='Task',
  full_name='Task',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='taskType', full_name='Task.taskType', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='setDevicePropertiesTask', full_name='Task.setDevicePropertiesTask', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='doDeviceCommandsTask', full_name='Task.doDeviceCommandsTask', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='setHostPropertiesTask', full_name='Task.setHostPropertiesTask', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='doHostCommandsTask', full_name='Task.doHostCommandsTask', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TASK_TASKTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=236,
  serialized_end=639,
)

_RPXMESSAGE.fields_by_name['firstOperation'].message_type = _OPERATION
_OPERATION.fields_by_name['tasks'].message_type = _TASK
_OPERATION.fields_by_name['nextOperation'].message_type = _OPERATION
_TASK.fields_by_name['taskType'].enum_type = _TASK_TASKTYPE
_TASK.fields_by_name['setDevicePropertiesTask'].message_type = tasktypes_pb2._SETDEVICEPROPERTIESTASK
_TASK.fields_by_name['doDeviceCommandsTask'].message_type = tasktypes_pb2._DODEVICECOMMANDSTASK
_TASK.fields_by_name['setHostPropertiesTask'].message_type = tasktypes_pb2._SETHOSTPROPERTIESTASK
_TASK.fields_by_name['doHostCommandsTask'].message_type = tasktypes_pb2._DOHOSTCOMMANDSTASK
_TASK_TASKTYPE.containing_type = _TASK;
DESCRIPTOR.message_types_by_name['RpxMessage'] = _RPXMESSAGE
DESCRIPTOR.message_types_by_name['Operation'] = _OPERATION
DESCRIPTOR.message_types_by_name['Task'] = _TASK

class RpxMessage(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RPXMESSAGE

  # @@protoc_insertion_point(class_scope:RpxMessage)

class Operation(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _OPERATION

  # @@protoc_insertion_point(class_scope:Operation)

class Task(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TASK

  # @@protoc_insertion_point(class_scope:Task)


# @@protoc_insertion_point(module_scope)
